#include <iostream>
#include <iomanip>

// Generated by GPT
class ArrayTools {
public:
    template <typename T>
    static void printArray(std::string _printMessage, const T* _array, size_t _arraySize) {
        std::cout << _printMessage << "[ ";
        for (size_t i = 0; i < _arraySize; ++i) {
            std::cout << _array[i];
            if (i < _arraySize - 1) {
                std::cout << ", ";
            }
        }
        std::cout << " ]" << std::endl;
    }
};
